export enum THEME_CONSTANTS {
    PRIMARY = '#1f7ac5',
    PRIMARY_LIGHT = '#64baff',
    PRIMARY_LIGHTER = '#cfe9ff',
    BACKDROP_COLOR = '#2681da80',
    INFO = '#1f7ac5ff',
    INFO_LIGHT = '#64baffff',
    SUCCESS = '#1a835f',
    SUCCESS_LIGHT = '#80eac6',
    WARNING = '#916b01',
    WARNING_LIGHT = '#ffba00',
    ERROR = '#bb2828',
    ERROR_LIGHT = '#f1a5a5',
    BORDER_COLOR = '#555555',
    TOAST = '#5f5f5f',
    TOOLTIP_COLOR = 'rgba(0,0,0,0.6)',
    BORDER_LIGHT_COLOR = '#eeeeee',
    BACKGROUND = '#ffffff',
    DISABLED_BACKGROUND = '#fafafa',
    DISABLED_BORDER = '#aaa',
    LIGHT_GREY = '#ccc',
    DISABLED = '#737373',
    TEXT_COLOR_LIGHT = '#fff',
    TEXT_COLOR_DARK = '#000',
    SHADOW = '0px 1px 3px 0px rgba(0,0,0,0.1), 0px 1px 2px 0px rgba(0,0,0,0.06)',
    HOVER_SHADOW = '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
    MODAL_SHADOW = '0px 8px 17px 2px rgba(0,0,0,0.14), 0px 3px 14px 2px rgba(0,0,0,0.12), 0px 5px 5px -3px rgba(0,0,0,0.2)',
}

export enum THEME_NAME {
    PRIMARY = '--nfui-primary',
    PRIMARY_LIGHT = '--nfui-primary-light',
    PRIMARY_LIGHTER = '--nfui-primary-lighter',
    INFO = '--nfui-info',
    INFO_LIGHT = '--nfui-info-light',
    SUCCESS = '--nfui-success',
    SUCCESS_LIGHT = '--nfui-success-light',
    WARNING = '--nfui-warning',
    WARNING_LIGHT = '--nfui-warning-light',
    ERROR = '--nfui-error',
    ERROR_LIGHT = '--nfui-error-light',
    BORDER_COLOR = '--nfui-border-color',
    TOAST = '--nfui-toast',
    TOOLTIP_COLOR = '--nfui-tooltip-color',
    BORDER_LIGHT_COLOR = '--nfui-border-light-color',
    BACKGROUND = '--nfui-background',
    DISABLED_BACKGROUND = '--nfui-disabled-background',
    DISABLED_BORDER = '--nfui-disabled-border',
    LIGHT_GREY = '--nfui-light-grey',
    DISABLED = '--nfui-disabled',
    TEXT_COLOR_LIGHT = '--nfui-text-color-light',
    TEXT_COLOR_DARK = '--nfui-text-color-dark',
    SHADOW = '--nfui-shadow',
    HOVER_SHADOW = '--nfui-hover-shadow',
    MODAL_SHADOW = '--nfui-modal-shadow',
    BACKDROP_COLOR = '--nfui-backdrop-color',
}

export const themeNameMap: Record<THEME_NAME, THEME_CONSTANTS> = {
    [THEME_NAME.PRIMARY]: THEME_CONSTANTS.PRIMARY,
    [THEME_NAME.PRIMARY_LIGHT]: THEME_CONSTANTS.PRIMARY_LIGHT,
    [THEME_NAME.PRIMARY_LIGHTER]: THEME_CONSTANTS.PRIMARY_LIGHTER,
    [THEME_NAME.INFO]: THEME_CONSTANTS.INFO,
    [THEME_NAME.INFO_LIGHT]: THEME_CONSTANTS.INFO_LIGHT,
    [THEME_NAME.SUCCESS]: THEME_CONSTANTS.SUCCESS,
    [THEME_NAME.SUCCESS_LIGHT]: THEME_CONSTANTS.SUCCESS_LIGHT,
    [THEME_NAME.WARNING]: THEME_CONSTANTS.WARNING,
    [THEME_NAME.WARNING_LIGHT]: THEME_CONSTANTS.WARNING_LIGHT,
    [THEME_NAME.ERROR]: THEME_CONSTANTS.ERROR,
    [THEME_NAME.ERROR_LIGHT]: THEME_CONSTANTS.ERROR_LIGHT,
    [THEME_NAME.BACKDROP_COLOR]: THEME_CONSTANTS.BACKDROP_COLOR,
    [THEME_NAME.BORDER_COLOR]: THEME_CONSTANTS.BORDER_COLOR,
    [THEME_NAME.TOAST]: THEME_CONSTANTS.TOAST,
    [THEME_NAME.TOOLTIP_COLOR]: THEME_CONSTANTS.TOOLTIP_COLOR,
    [THEME_NAME.BORDER_LIGHT_COLOR]: THEME_CONSTANTS.BORDER_LIGHT_COLOR,
    [THEME_NAME.BACKGROUND]: THEME_CONSTANTS.BACKGROUND,
    [THEME_NAME.DISABLED_BACKGROUND]: THEME_CONSTANTS.DISABLED_BACKGROUND,
    [THEME_NAME.DISABLED_BORDER]: THEME_CONSTANTS.DISABLED_BORDER,
    [THEME_NAME.LIGHT_GREY]: THEME_CONSTANTS.LIGHT_GREY,
    [THEME_NAME.DISABLED]: THEME_CONSTANTS.DISABLED,
    [THEME_NAME.TEXT_COLOR_LIGHT]: THEME_CONSTANTS.TEXT_COLOR_LIGHT,
    [THEME_NAME.TEXT_COLOR_DARK]: THEME_CONSTANTS.TEXT_COLOR_DARK,
    [THEME_NAME.SHADOW]: THEME_CONSTANTS.SHADOW,
    [THEME_NAME.HOVER_SHADOW]: THEME_CONSTANTS.HOVER_SHADOW,
    [THEME_NAME.MODAL_SHADOW]: THEME_CONSTANTS.MODAL_SHADOW,
};

export const getThemeValue = (key: THEME_NAME) => {
    return `var(${key}, ${themeNameMap[key]})`;
};
